### ISSUE TITLE
Add basic golang project structure

### ISSUE THREAD

**Issue by cbrgm** [nilo72/owncloud_exporter#1]
TODO: Create a basic structure for the Prometheus Exporter. 
Maybe forking project https://github.com/promhippie/owncloud_exporter.

**Comment by nilo72** [comment]
Maybe creating a new structure that fits our needs we talked about. Absolutly not sure what the best way ist.

**Comment by cbrgm** [comment]
Could you please give me permission to push to this repo?  See haw-hh-inf slack :-)

**Comment by nilo72** [comment]
I sent an invitation days ago...

**Comment by cbrgm** [comment]
Thanks!
